#!/usr/bin/env python3
"""Generate all manuscript and supplementary tables from public outputs."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
TABLES=ROOT/"manuscript/tables"
TABLES.mkdir(parents=True,exist_ok=True)
FAMS=["learned","sinusoidal","rope","alibi"]
LABEL={"learned":"Learned","sinusoidal":"Sinusoidal","rope":"RoPE","alibi":"ALiBi"}

def write(name,lines):
    (TABLES/name).write_text("\n".join(lines).rstrip()+"\n",encoding="utf-8")

def main():
    global TABLES
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=TABLES)
    parser.add_argument(
        "--primary-table-source",
        type=Path,
        default=ROOT / "analysis/canonical_cohorts/reference_outputs/table_primary_nauc_v18.tex",
    )
    parser.add_argument(
        "--wide-table-source",
        type=Path,
        default=ROOT / "analysis/canonical_cohorts/reference_outputs/table_cifar_wide_v18.tex",
    )
    parser.add_argument(
        "--clean-table-source",
        type=Path,
        default=ROOT / "analysis/clean_accuracy/reference_outputs/table_clean_accuracy.tex",
    )
    parser.add_argument(
        "--no-envelope-table-source",
        type=Path,
        default=ROOT / "analysis/canonical_cohorts/reference_outputs/table_no_envelope_sensitivity.tex",
    )
    parser.add_argument(
        "--postlock-table-source",
        type=Path,
        default=ROOT / "analysis/cross_cohort/reference_outputs/table_postlock_grid_sensitivity.tex",
    )
    args = parser.parse_args()
    TABLES = args.output_dir
    TABLES.mkdir(parents=True, exist_ok=True)

    # Canonical tables are generated by the canonical analysis pipeline.
    for source, name in (
        (args.primary_table_source, "table_primary_nauc.tex"),
        (args.wide_table_source, "table_cifar_wide.tex"),
    ):
        if not source.exists():
            raise SystemExit(f"Missing canonical table source: {source}")
        (TABLES / name).write_bytes(source.read_bytes())

    # Table 1 is generated by the dedicated clean-accuracy pipeline.
    clean = args.clean_table_source
    if not clean.exists():
        raise SystemExit("Run analysis/clean_accuracy/build_clean_accuracy_table.py first")
    (TABLES/"table_clean_accuracy.tex").write_bytes(clean.read_bytes())

    # Factorial design table (design metadata, generated to avoid inline drift).
    write("table_factorial_comparison_design.tex",[
      r"\begin{table*}[t]",r"\centering",r"\small",
      r"\caption{Three complementary comparisons used to separate system-level,",
      r"training-regime, and architecture contrasts.}",
      r"\label{tab:factorial-comparison-design}",
      r"\resizebox{\textwidth}{!}{%",r"\begin{tabular}{lllll}",r"\toprule",
      r"Analysis & Architecture contrast & Training contrast & Shared PE families & Inferential role \\",
      r"\midrule",
      r"Canonical & ViT-B vs ViT-S & AMP vs full FP32 & 4 & System-level replication; factors confounded \\",
      r"Within-ViT-S regime & ViT-S fixed & AMP vs full FP32 & 3 & Within-backbone training-regime comparison \\",
      r"AMP-matched architecture & ViT-B vs ViT-S & AMP fixed & 3 & Cross-architecture effect with training regime fixed \\",
      r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table*}"
    ])

    # Canonical cross-architecture nAUC table.
    agg=pd.read_csv(ROOT/"analysis/cross_cohort/reference_bundle/v19_support_aware_aggregate_nauc.csv")
    q=agg.query("scope=='cross' and endpoint_multiplier==1.0")
    def val(arch,fam,metric):
        r=q.query("architecture==@arch and family==@fam and metric==@metric").iloc[0]
        return float(r["mean"]),float(r["sd"])
    lines=[
      r"\begin{table*}[t]",r"\centering",r"\small",
      r"\caption{Cross-architecture ImageNet-100 nAUC over the locked common-support",
      r"interval $\rho_{\mathrm{rel}}\in[0,0.07924]$. Values are mean $\pm$",
      r"sample SD across six seeds.}",
      r"\label{tab:cross-architecture-nauc}",
      r"\resizebox{\textwidth}{!}{%",r"\begin{tabular}{llccc}",r"\toprule",
      r"Architecture & PE family & Noise nAUC & Adversarial nAUC & Gap \\",
      r"\midrule",
    ]
    for ai,arch in enumerate(["vitb","vits"]):
        for fi,fam in enumerate(FAMS):
            n=val(arch,fam,"noise_nauc"); a=val(arch,fam,"adversarial_nauc"); g=val(arch,fam,"gap")
            arch_label="ViT-B/16" if arch=="vitb" else "ViT-S/16"
            lines.append(f"{arch_label if fi==0 else ''} & {LABEL[fam]} & "
                         f"${n[0]:.4f} \\pm {n[1]:.4f}$ & "
                         f"${a[0]:.4f} \\pm {a[1]:.4f}$ & "
                         f"${g[0]:.4f} \\pm {g[1]:.4f}$ \\\\")
        if ai==0: lines.append(r"\midrule")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table*}"]
    write("table_cross_architecture_nauc.tex",lines)

    # AMP-matched architecture table.
    attack=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_ATTACK_MAIN_TABLE_v2.csv")
    welch=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_WELCH_SENSITIVITY_v2.csv")
    lines=[
      r"\begin{table*}[t]",r"\centering",r"\scriptsize",
      r"\caption{AMP-matched ImageNet-100 adversarial nAUC over",
      r"$\rho_{\mathrm{rel}}\in[0,0.08735]$. Architecture values are mean",
      r"$\pm$ sample SD across six seeds; $\Delta$ is ViT-S minus ViT-B. Exact",
      r"sign-flip values are secondary directional-consistency checks.}",
      r"\label{tab:amp-matched-nauc}",r"\resizebox{\textwidth}{!}{%",
      r"\begin{tabular}{lccccccc}",r"\toprule",
      r"PE family & ViT-B adversarial nAUC & ViT-S adversarial nAUC & $\Delta$ adversarial & Seed-aligned 95\% CI & Seeds $\Delta<0$ & Exact $p$ & $\Delta$ noise nAUC \\",
      r"\midrule",
    ]
    for fam in ["learned","sinusoidal","rope"]:
        a=attack.query("family==@fam").iloc[0]
        n=welch.query("family==@fam and metric=='noise_nauc'").iloc[0]
        lines.append(f"{a.family_label} & ${a.vitb_mean:.4f}\\pm{a.vitb_sd:.4f}$ & "
                     f"${a.vits_mean:.4f}\\pm{a.vits_sd:.4f}$ & "
                     f"${a.mean_delta_vits_minus_vitb:.4f}$ & "
                     f"$[{a.ci95_t_low:.4f},{a.ci95_t_high:.4f}]$ & "
                     f"{int(a.negative_deltas)}/6 & {a.exact_sign_flip_p_two_sided:.5f} & "
                     f"${n.mean_delta_vits_minus_vitb:+.6f}$ \\\\")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table*}"]
    write("table_amp_matched_nauc.tex",lines)

    # Same-seed objective comparison, using calibration-split rho for both objectives.
    direct=json.loads((ROOT/"data/objective_specific/direct_displacement/D020_VITS_FORMAL_CENTRAL_ENDPOINT_v1.json").read_text())
    audit=pd.read_csv(ROOT/"data/objective_specific/all_restart_audit/POINT_SELECTION_SUMMARY_v1.csv")
    task=audit.query("architecture=='vits' and seed==42").set_index("budget")
    rows=[]
    for budget,key in [(0.0095,"budget_0p0095_locked_200"),(0.0200,"budget_0p020_locked_200")]:
        d=direct[key]
        rows.append((budget,"direct-$\\rho$",d["calibration_rho_rel"],d["accuracy"]))
        t=task.loc[budget]
        rows.append((budget,"task loss",float(t.loss_selected_rho_rel),float(t.loss_selected_accuracy)))
    lines=[
      r"\begin{table}[t]",r"\centering",
      r"\caption{Same-seed, same-budget comparison for ViT-S/16 FP32 Sinusoidal",
      r"seed 42. Reported $\rho_{\mathrm{rel}}$ values are measured on the common",
      r"256-image calibration split; accuracies use the 3,464-image evaluation split.}",
      r"\label{tab:objective-comparison}",r"\begin{tabular}{llrr}",r"\toprule",
      r"Budget & Objective & $\rho_{\mathrm{rel}}$ & Accuracy (\%) \\",r"\midrule",
    ]
    for b,obj,rho,acc in rows:
        lines.append(f"{b:.4f} & {obj} & {rho:.5f} & {acc:.2f} \\\\")
    lines += [r"\bottomrule",r"\end{tabular}",r"\end{table}"]
    write("table_objective_comparison.tex",lines)

    # Supplement S1: Welch.
    w=welch[welch.metric.isin(["attack_nauc","noise_nauc"])].copy()
    lines=[r"\begin{table}[H]",r"\centering",
      r"\caption{Seed-aligned and unpaired Welch 95\% intervals for ViT-S minus",
      r"ViT-B nAUC contrasts. Both interval constructions give the same",
      r"interpretive conclusion for every family and metric.}",
      r"\label{tab:s-welch}",r"\small",r"\resizebox{\textwidth}{!}{%",
      r"\begin{tabular}{llrrr}",r"\toprule",
      r"PE family & Metric & Mean difference & Seed-aligned 95\% CI & Welch 95\% CI \\",
      r"\midrule"]
    for metric,label in [("attack_nauc","Adversarial nAUC"),("noise_nauc","Noise nAUC")]:
        for fam in ["learned","sinusoidal","rope"]:
            r=w.query("family==@fam and metric==@metric").iloc[0]
            lines.append(f"{r.family_label} & {label} & {r.mean_delta_vits_minus_vitb:.6f} & "
                         f"$[{r.paired_ci95_low:.6f}, {r.paired_ci95_high:.6f}]$ & "
                         f"$[{r.welch_ci95_low:.6f}, {r.welch_ci95_high:.6f}]$ \\\\")
        if metric=="attack_nauc": lines.append(r"\midrule")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table}"]
    write("table_s_welch.tex",lines)

    # Supplement S2: ordinal.
    ords=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_INTERACTION_ORDINAL_ROBUSTNESS_v2.csv")
    lines=[r"\begin{table}[H]",r"\centering",r"\caption{Per-seed ordering of adversarial architecture effects.}",
      r"\label{tab:s-orders}",r"\small",r"\resizebox{\textwidth}{!}{%",
      r"\begin{tabular}{rccc l}",r"\toprule",
      r"Seed & Learned $\Delta$ & Sinusoidal $\Delta$ & RoPE $\Delta$ & Ascending order \\",
      r"\midrule"]
    for _,r in ords.iterrows():
        order=r.ascending_order.replace("sinusoidal","Sinusoidal").replace("learned","Learned").replace("rope","RoPE").replace("<","$<$")
        lines.append(f"{int(r.seed)} & {r.learned_delta:.6f} & {r.sinusoidal_delta:.6f} & {r.rope_delta:.6f} & {order} \\\\")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table}"]
    write("table_s_orders.tex",lines)

    # Supplement S3: pairwise DID.
    did=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_INTERACTION_PAIRWISE_DID_v2.csv")
    pretty={"learned_minus_rope":"Learned $-$ RoPE","sinusoidal_minus_rope":"Sinusoidal $-$ RoPE","learned_minus_sinusoidal":"Learned $-$ Sinusoidal"}
    order=["learned_minus_rope","sinusoidal_minus_rope","learned_minus_sinusoidal"]
    lines=[r"\begin{table}[H]",r"\centering",
      r"\caption{Pairwise differences in architecture effects. Same-sign counts",
      r"refer to the dominant sign across the six seeds.}",r"\label{tab:s-did}",r"\small",
      r"\resizebox{\textwidth}{!}{%",r"\begin{tabular}{lrr}",r"\toprule",
      r"Difference-in-differences contrast & 95\% CI & Same-sign seeds \\",r"\midrule"]
    for c in order:
        r=did.query("contrast==@c").iloc[0]
        lines.append(f"{pretty[c]} & $[{r.ci95_t_low:.6f}, {r.ci95_t_high:.6f}]$ & "
                     f"{int(r.same_sign_seeds)}/6 {r.dominant_sign} \\\\")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table}"]
    write("table_s_did.tex",lines)

    # Supplement S4: dispersion.
    disp=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_ARCHITECTURE_DISPERSION_AUDIT_v2.csv")
    lines=[r"\begin{table}[H]",r"\centering",
      r"\caption{Seed dispersion of adversarial nAUC. The leave-one-out range is",
      r"the minimum and maximum ViT-S/ViT-B SD ratio after omitting each seed in turn.}",
      r"\label{tab:s-dispersion}",r"\small",r"\resizebox{\textwidth}{!}{%",
      r"\begin{tabular}{lrrrrrr}",r"\toprule",
      r"PE family & ViT-B range & ViT-S range & ViT-B SD & ViT-S SD & SD ratio & LOO SD-ratio range \\",
      r"\midrule"]
    for fam in ["learned","rope","sinusoidal"]:
        r=disp.query("family==@fam").iloc[0]
        lines.append(f"{r.family_label} & {r.vitb_range:.6f} & {r.vits_range:.6f} & "
                     f"{r.vitb_sd:.6f} & {r.vits_sd:.6f} & {r.sd_ratio_vits_over_vitb:.3f} & "
                     f"$[{r.loo_sd_ratio_min:.3f}, {r.loo_sd_ratio_max:.3f}]$ \\\\")
    lines += [r"\bottomrule",r"\end{tabular}%",r"}",r"\end{table}"]
    write("table_s_dispersion.tex",lines)

    # Supplement S5: sign balance.
    sign=pd.read_csv(ROOT/"analysis/cross_architecture/reference_outputs/D059_ATTACK_NOISE_SIGN_BALANCE_v2.csv")
    lines=[r"\begin{table}[H]",r"\centering",
      r"\caption{Seed signs for ViT-S minus ViT-B nAUC contrasts.}",
      r"\label{tab:s-signs}",r"\begin{tabular}{lrrrr}",r"\toprule",
      r"PE family & Attack $\Delta<0$ & Attack $\Delta>0$ & Noise $\Delta<0$ & Noise $\Delta>0$ \\",
      r"\midrule"]
    for fam in ["learned","sinusoidal","rope"]:
        a=sign.query("family==@fam and metric=='attack_nauc'").iloc[0]
        n=sign.query("family==@fam and metric=='noise_nauc'").iloc[0]
        lines.append(f"{a.family_label} & {int(a.negative_seeds)} & {int(a.positive_seeds)} & "
                     f"{int(n.negative_seeds)} & {int(n.positive_seeds)} \\\\")
    lines += [r"\bottomrule",r"\end{tabular}",r"\end{table}"]
    write("table_s_signs.tex",lines)

    # Existing generated sensitivity tables.
    for src, name in [
        (args.no_envelope_table_source, "table_no_envelope_sensitivity.tex"),
        (args.postlock_table_source, "table_postlock_grid_sensitivity.tex"),
    ]:
        if not src.exists():
            raise SystemExit(f"Missing sensitivity table source: {src}")
        (TABLES / name).write_bytes(src.read_bytes())

    expected = {
        "table_primary_nauc.tex",
        "table_cifar_wide.tex",
        "table_clean_accuracy.tex",
        "table_factorial_comparison_design.tex",
        "table_cross_architecture_nauc.tex",
        "table_amp_matched_nauc.tex",
        "table_objective_comparison.tex",
        "table_s_welch.tex",
        "table_s_orders.tex",
        "table_s_did.tex",
        "table_s_dispersion.tex",
        "table_s_signs.tex",
        "table_no_envelope_sensitivity.tex",
        "table_postlock_grid_sensitivity.tex",
    }
    produced = {path.name for path in TABLES.glob("*.tex")}
    if produced != expected:
        raise SystemExit(
            f"Unexpected manuscript-table set: missing={sorted(expected-produced)}, "
            f"extra={sorted(produced-expected)}"
        )
    print("Generated manuscript tables:", len(produced))

if __name__=="__main__":
    main()
